- hosts: localhost
  
  tasks:
  - debug: msg="{{ lookup('env','BUILD_TAG') }}"

  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    user:
      name: {{ user_to_add }}
      comment: User {{ user_to_add }} Created by Jenkins/Ansible

  - name: check file exists.
    stat:
      path: "{{ filepath }}"
    register: file_details

  - debug:
      msg: "The file or directory exists {{ file_details }}"
    when: file_details.stat.exists