- hosts: localhost
  tasks:
  
  tasks:
  - debug: msg="{{ lookup('env','BUILD_TAG') }}"

  - name: check file exists.
    stat:
      path: "{{ public.key }}"
    register: file_details

  - debug:
      msg: "The file or directory exists {{ file_details }}"
    when: file_details.stat.exists