- hosts: localhost
  
  tasks:
  - debug: msg="{{ lookup('env','BUILD_TAG') }}"

  - name: Add user
    user:
      name: "{{ user_to_add }}"
      state: present
      comment: User {{ user_to_add }} Created by Jenkins/Ansible
      become: true
      become_user: "{{ login }}"

  - name: Check file exists.
    stat:
      path: "{{ filepath }}"
    register: file_details

  - debug:
      msg: "The file or directory exists {{ file_details }}"
    when: file_details.stat.exists